# Generated by Django 4.2.11 on 2024-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0506_realm_require_unique_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmuserdefault",
            name="enable_dm_silent_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enable_dm_silent_mode",
            field=models.BooleanField(default=False),
        ),
    ]
