# Generated by Django 5.0.6 on 2024-07-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0526_alter_archivedusermessage_flags_and_more"),
        ("zerver", "0558_realmuserdefault_web_animate_image_previews_and_more"),
    ]

    operations = []
